#index:
#    path: /
#    controller: App\Controller\DefaultController::index

college_check:
  path: /college/check
  controller: App\Controller\CollegeController::check

college_details:
  path: /college/details
  controller: App\Controller\CollegeController::details
